# Generated by Django 4.1.7 on 2023-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categoriestitle_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.category'),
        ),
    ]
